### ISSUE TITLE
Investigate random ingest

### ISSUE THREAD

**Issue by jeffbaumes** [XDATA-Year-3/geoapp#10]

**Comment by manthey** [comment]
I loaded the 1/12th dataset in random order.  When I query it, if I always sort the results on `_id`, and limit the results to a maximum of 300,000 points, it has some interesting advantages over the non-randomized data:
- The worst-case query time was around 40 seconds.  For the non-randomized data, trying to get a random-subset took minutes (or longer) because Windows (or my hard drive) is terrible at seeking back and forth.  Also on the non-randomized data, complex queries seemed really slow (such as a pickup date range and a distance range), whereas this seems to never be much slower.
- By always sorting via `_id`, I don't get particular speed-ups for common queries (like pickup_datetime), but I do for matching values (e.g., `medallion` = `9Y64`).  This can probably be alleviated by compound indices involving `_id` and common range queries.

**Comment by manthey** [comment]
Another minor mongo optimization: if the queried data is small enough that my limit doesn't restrict the data, then I don't need to sort the data -- the javascript isn't expected the data in a sorted order anyway.  Therefore, I can first make a mongo query _without_ a sort, check the `count` against my limit, and, if it is smaller, use that cursor to fetch data.  If the `count` is larger than the limit, I still need to sort the data to ensure that I get what looks like a random sampling (or, for non-randomized data, the initial date range).

For the 1/12th shuffled database returning 297,000 points, this is much faster (in a 'warmed up database', 3 or 4 seconds without sorting versus ~35 seconds with sorting), regardless of which indices I seem to have on the sort and query fields.  Strictly, if the sort and query are both on the same field _and_ the database was loaded in approximately the sort order, then mongo is fast with the sorted data, too.

Oddly, when I want to filter by a pickup date range and sort by _id, it doesn't seem to affect the query time regardless of whether I have or hint indices for `date`, `_id`, `[date, _id]`, or `[_id, date]` -- they all seem roughly equal in the query time when the database has been 'warmed up'.

**Comment by jeffbaumes** [comment]
I may be missing something, but why do you need to sort at all if you are using the shuffled database? Do you still need to sort by `_id` even if that matches the natural order?

**Comment by manthey** [comment]
I don't know how one knows if the natural order is the functionally identical to the _id order.  I imagine that if we never update any data _and_ only create the indices after the data is loaded, then it would be so.

**Comment by jeffbaumes** [comment]
You are right that natural order is fragile. It seems it should agree with insertion order if you don't edit anything. From http://docs.mongodb.org/manual/reference/method/cursor.sort/#return-natural-order

> The $natural parameter returns items according to their natural order within the database. This ordering is an internal implementation feature, and you should not rely on any particular structure within it.
> 
> Typically, the natural order reflects insertion order, except when documents relocate because of document growth due to updates or remove operations free up space which are then taken up by newly inserted documents.

**Comment by jeffbaumes** [comment]
It also seems that this is not necessarily the default return order, you need to explicitly ask for natural order. But a comparison between sorting by `_id` and specifying `$natural` might be interesting to try someday.

**Comment by manthey** [comment]
Ultimately, the random order load into Postgres seems to give the best overall performance.  See docs/databases.rst for a performance comparison.
