### ISSUE TITLE
UI: need separation between taxi and twitter filtering UI

### ISSUE THREAD

**Issue by zachmullen** [XDATA-Year-3/geoapp#145]
We could put them in two separate panels, or two tabs within the same panel. Right now it is not clear what each filter button is referring to.

Also, one other minor nit: a lot of analysts did not recognize that the filter button was a button, presumably because it was the same color as the surrounding area. I would suggest making it blue like the other buttons in the app.

**Comment by zachmullen** [comment]
@manthey I'm happy to fix this if you describe your preferred solution :)

**Comment by manthey** [comment]
It looks like we are getting new data for July.  Once we figure out what
that fully implies, I'll have a better idea of what we should do.

On Mon, Jun 29, 2015 at 11:32 AM, Zach Mullen notifications@github.com
wrote:

> @manthey https://github.com/manthey I'm happy to fix this if you
> describe your preferred solution :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/XDATA-Year-3/geoapp/issues/145#issuecomment-116733251
> .

## 

David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439

**Comment by jamiesnape** [comment]
One of my users also suggested a taxi panel and a message panel. Same user as #164.

**Comment by manthey** [comment]
Some filtering options apply to both.  For instance, the July data set will have multiple cities' data, so we will have a region selector that lets you pick 'All' or a specific city.  The date current _can_ be grouped, but doesn't have to be.

Some display options apply to both (you can load more points than you display, for instance, so that you can have accurate heat map bins without crushing your GPU when looking at just points).

To further complicate things, some of the data for July is point-to-point data that ISN'T taxi data (Washington D.C. bike share data, for instance).

We've had the thought of having the panels have a simple mode and a lots-of-features mode.  This would hide the rarely used controls, but allow them to be shown when a + button was selected.  For instance, the taxi trip length and number of passenger controls would fall into this group.

One possibility would be instead of "Filters" and "Display", there was "General", "Trips", and "Messages".
"General" would have Region (what city), Date, Map Source, and the Location buttons (and the legend?).  
"Trips" and "Messages" would have advanced (default hidden) options for "Use a different date" and their own date range.  Otherwise, they would have a prominent "Show" button (which, when toggled would grey out the rest of the controls).  Each would have the Filter and max controls.  The Trips would have the taxi-specific controls (the trip length, number of passengers, Display Type, and Processing), and the Messages would have the text search.

I currently have the "Max Points" control in the Display section (which changes to a "Max Vectors" control at times.  I guess this would remain in the Trips section and a dual of it would be in the messages section (so you can load more messages for binning or graphing than are drawn on the map).

Thoughts?

**Comment by zachmullen** [comment]
> We've had the thought of having the panels have a simple mode and a lots-of-features mode. This would hide the rarely used controls, but allow them to be shown when a + button was selected. For instance, the taxi trip length and number of passenger controls would fall into this group.

At least one analyst requested such a "simple vs. advanced" mode switch.

> One possibility would be instead of "Filters" and "Display", there was "General", "Trips", and "Messages".
> "General" would have Region (what city), Date, Map Source, and the Location buttons (and the legend?).

This sounds good. If this moves us toward increased flexibility as far as what sorts of data we can handle, I'm all for it. I think the power of this application will be in how easily we can tailor it to be useful on new datasets that might be a little different from what we have currently. I do like having just a single date range for data filtering -- I can't imagine someone would want to load data from two different date ranges at once depending on the type of data.

**Comment by jamiesnape** [comment]
People may want to look at the same data set at two different points in time on the same map, but that is a different situation.

**Comment by manthey** [comment]
This has been addressed in PR #201.
