### ISSUE TITLE
Use abbreviated month names

### ISSUE THREAD

**Issue by jeffbaumes** [XDATA-Year-3/geoapp#96]
I think using 3-letter month abbreviations in the Instagram results, Instagram overlay, chart axes, and chart tooltip will be more readable, perhaps using the format "Jan 1, 2013 09:45" with shorter forms of this where appropriate. Search ranges are less clear because of the nice direct-edit functionality that relies on the ISO formatted date/time, so I'd leave that as-is for now.

**Comment by manthey** [comment]
@jeffbaumes It is easy to change everything except the date picker widget (which is called daterangepicker).  For that, I can change to a different format (such as '2013 Jan 4 13:23'), but I can't easily make it accept dates flexibly.  I'd love to see it be more forgiving and have a default year, so that you could type 'Mar 4' and it would know that was 2013-03-04.  Internally, daterangepicker uses momentjs, but it always specifies an explicit format for parsing.

I can do any of the following: (a) leave the daterangepicker in YYYY-MM-DD HH:mm format, (b) switch to another format, but it would still require year to be entered and displayed (for instance, YYYY MMM D HH:mm would allow and require formats such as '2013 Mar 4'), (c) fork daterangepicker and make it so we can specify dates much more liberally, (d) switch to a different widget (though I have no suggestions).

**Comment by jeffbaumes** [comment]
I think as long as it's changed everywhere else I'm not too concerned about fixing the date picker. Normally you will be using the date picker to click on dates anyway and month abbreviations appear in the calendar views.

**Comment by manthey** [comment]
Added in PR #100.
